# Generated by Django 3.2.5 on 2022-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0002_auto_20220616_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='size',
            field=models.CharField(choices=[('U', 'Unkown'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='U', max_length=1),
        ),
    ]
