# Generated by Django 3.2.5 on 2022-06-20 18:52

import coffe_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0003_store_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(error_messages={'max_length': 'Enter exactly 11 digit', 'required': 'Enter your mobile number'}, help_text='Mobile number', max_length=11, validators=[django.core.validators.RegexValidator(code='Invalid', message="Phone number must be entered in the format:'09999999999'. Up to 11 digits allowd.", regex='^09\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(30)])),
                ('description', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('U', 'Unkown'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('calories', models.IntegerField(validators=[coffe_app.models.calorie_watcher])),
            ],
        ),
    ]
